# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
#- task: DotNetCoreInstaller@0
#  inputs:
#    version: '2.1.300'
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.202'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: DotNetCoreCLI@2
  condition: 
  displayName: 'Tests'
  inputs:
    command: 'test'
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop